FROM node:16.10.0
LABEL authors="Dream Machines"

WORKDIR /app

COPY ./package*.json /app/

RUN npm install

COPY . .

ENV REACT_APP_BACKEND_PORT=8000
ENV REACT_APP_BACKEND_DOMAIN=http://127.0.0.1:
ENV REACT_APP_BACKEND_HOST=${REACT_APP_BACKEND_DOMAIN}${REACT_APP_BACKEND_PORT}/
ENV REACT_APP_BACKEND_AUTH=${REACT_APP_BACKEND_HOST}auth
ENV REACT_APP_BACKEND_API=${REACT_APP_BACKEND_HOST}api
ENV REACT_APP_CAPTCHA_KEY=6LdsIJwpAAAAAJWPQM3kba8OFydXDXMryCQIOK8i
ENV REACT_APP_CAPTCHA_SECRET=6LdsIJwpAAAAALgAChivSeoREG74wVXq__V6V2vh
ENV REACT_APP_YOUTUBE_API_KEY=AIzaSyBiiAS9i56Zy6FNQlSR2GXeLX_B94qcNZA

EXPOSE 3000

CMD ["npm", "start"]